{{- $threads := 1 }}
{{- if .Values.resources.limits.cpu }}
  {{- if typeIs "string" .Values.resources.limits.cpu }}
    {{- $trimmed := trimSuffix "m" .Values.resources.limits.cpu }}
    {{- $value := ternary (float64 $trimmed | ceil | mul 1000) $trimmed (contains "." $trimmed) | int64 }}
    {{- if eq (mod $value 1000) 0 }}
      {{- $threads = div $value 1000 }}
    {{- else }}
      {{- $threads = add1 (div $value 1000) }}
    {{- end }}
  {{- else }}
    {{- $threads = .Values.resources.limits.cpu }}
  {{- end }}
{{- end }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ template "tuwunel.fullname" . }}
  labels:
    {{- include "tuwunel.labels" . | nindent 4 }}
    app.kubernetes.io/component: tuwunel
  {{- with .Values.statefulsetAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  serviceName: {{ template "tuwunel.fullname" . }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "tuwunel.labels" . | nindent 6 }}
      app.kubernetes.io/component: tuwunel
  template:
    metadata:
      labels:
        {{- include "tuwunel.labels" . | nindent 8 }}
        app.kubernetes.io/component: tuwunel
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2020
        runAsGroup: 2020
        fsGroupChangePolicy: OnRootMismatch
        fsGroup: 2020
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: config-processor
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
          imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - envsubst < /tmp/config-template/config.toml > /tmp/config/config.toml
          {{- if or (.Values.env) (.Values.envRaw) (.Values.envFromSecret) }}
          env:
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.envRaw }}
            {{- with .Values.envRaw }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- range $key, $val := .Values.envFromSecret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ (split "/" $val)._0 }}
                  key: {{ (split "/" $val)._1 }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: config-template
              mountPath: /tmp/config-template
            - name: config
              mountPath: /tmp/config
            - name: tmp
              mountPath: /tmp
      containers:
        - name: tuwunel
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /data
              name: data
              subPath: data
            - mountPath: /tmp/config
              name: config
            - mountPath: /tmp
              name: tmp
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: TOKIO_WORKER_THREADS
              value: {{ $threads | quote }}
            - name: CONDUWUIT_CONFIG
              value: "/tmp/config/config.toml"
            - name: CONDUWUIT_SERVER_NAME
              value: {{ required "You must set a server name otherwise no one will be able to reach you" .Values.server_name | quote }}
            - name: CONDUWUIT_DATABASE_PATH
              value: "/data/db"
            - name: CONDUWUIT_PORT
              value: "8080"
            - name: CONDUWUIT_ADDRESS
              value: "0.0.0.0"
            - name: CONDUWUIT_ROCKSDB_PARALLELISM_THREADS
              value: {{ $threads | quote }}
            - name: RUST_LOG
              value: info
            {{- range .Values.extraEnv }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /_matrix/federation/v1/version
              port: http
            periodSeconds: 2
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      volumes:
        - name: data
          {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim | default (printf "%s-%s" (include "tuwunel.fullname" .) "data") }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: config-template
          configMap:
            name: {{ template "tuwunel.fullname" . }}-configmap
        - name: config
          emptyDir: {}
        - name: tmp
          emptyDir: {}
