{{- if .Values.rtc.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tuwunel.fullname" . }}-jwt
  labels:
    {{- include "tuwunel.labels" . | nindent 4 }}
    app.kubernetes.io/component: rtc-jwt
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tuwunel.labels" . | nindent 6 }}
      app.kubernetes.io/component: rtc-jwt
  template:
    metadata:
      labels:
        {{- include "tuwunel.labels" . | nindent 8 }}
        app.kubernetes.io/component: rtc-jwt
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: jwt-service
          image: "{{ .Values.rtc.jwt.image.repository }}:{{ .Values.rtc.jwt.image.tag }}"
          imagePullPolicy: {{ .Values.rtc.jwt.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          {{- if or (.Values.rtc.jwt.env) (.Values.rtc.jwt.envRaw) (.Values.rtc.jwt.envFromSecret) }}
          env:
          {{- range $key, $val := .Values.rtc.jwt.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.rtc.jwt.envRaw }}
            {{- with .Values.rtc.jwt.envRaw }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- range $key, $val := .Values.rtc.jwt.envFromSecret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ (split "/" $val)._0 }}
                  key: {{ (split "/" $val)._1 }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.rtc.jwt.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}
