{{- if .Values.rtc.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tuwunel.fullname" . }}-livekit
  labels:
    {{- include "tuwunel.labels" . | nindent 4 }}
    app.kubernetes.io/component: rtc-livekit
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.rtc.livekit.config.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "tuwunel.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rtc-livekit
{{- end }}
