{{- if .Values.rtc.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tuwunel.fullname" . }}-livekit
  labels:
    {{- include "tuwunel.labels" . | nindent 4 }}
    app.kubernetes.io/component: rtc-livekit
  annotations:
    {{- with .Values.rtc.livekit.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ if eq .Values.rtc.livekit.networkMode "loadBalancer" }}{{ .Values.rtc.livekit.service.type }}{{ else }}ClusterIP{{ end }}
  {{- if and (eq .Values.rtc.livekit.networkMode "loadBalancer") .Values.rtc.livekit.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.rtc.livekit.service.externalTrafficPolicy }}
  {{- end }}
  {{- if and (eq .Values.rtc.livekit.networkMode "loadBalancer") .Values.rtc.livekit.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.rtc.livekit.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.rtc.livekit.config.port }}
      targetPort: http
      protocol: TCP
    {{- if eq .Values.rtc.livekit.networkMode "loadBalancer" }}
    - name: rtc-tcp
      port: {{ .Values.rtc.livekit.config.rtc.tcp_port }}
      targetPort: rtc-tcp
      protocol: TCP
    {{- $start := int .Values.rtc.livekit.config.rtc.port_range_start }}
    {{- $end := int .Values.rtc.livekit.config.rtc.port_range_end }}
    {{- range $i := until (int (sub $end $start)) }}
    - name: rtc-udp-{{ add $start $i }}
      port: {{ add $start $i }}
      targetPort: {{ add $start $i }}
      protocol: UDP
    {{- end }}
    {{- end }}
  selector:
    {{- include "tuwunel.labels" $ | nindent 4 }}
    app.kubernetes.io/component: rtc-livekit
{{- end }}
