apiVersion: v2
appVersion: v1.5.0
description: Helm chart for tuwunel - a Matrix homeserver based on Conduit with optional LiveKit RTC support
home: https://github.com/arsolitt/tuwunel-helm
keywords:
- tuwunel
- matrix
- homeserver
- conduit
- livekit
- element-call
- rtc
maintainers:
- email: arsolitt@gmail.com
  name: arsolitt
  url: https://github.com/arsolitt
name: tuwunel
sources:
- https://github.com/arsolitt/tuwunel-helm
type: application
version: 1.0.1
