apiVersion: v2
appVersion: v1.5.1
description: Helm chart for tuwunel - a Matrix homeserver based on Conduit with optional LiveKit RTC support
home: https://github.com/Arsolitt/tuwunel-helm
keywords:
- tuwunel
- matrix
- homeserver
- conduit
- livekit
- element-call
- rtc
maintainers:
- email: arsolitt@gmail.com
  name: Arsolitt
  url: https://github.com/Arsolitt
name: tuwunel
sources:
- https://github.com/Arsolitt/tuwunel-helm
- https://github.com/matrix-construct/tuwunel
type: application
version: 1.1.0
