apiVersion: v1
appVersion: 2.1.0
description: A modern and maintained fork of conduwuit
home: https://github.com/magikid/modern-conduwuit-helm
keywords:
- tuwunel
- matrix
- homeserver
- conduwuit
- continuwuity
maintainers:
- email: chris@mystic.horse
  name: magikid
name: conduwuit
sources:
- https://gitlab.cronce.io/charts/conduwuit
- https://github.com/AreYouLoco/tuwunel-helm
version: 2.1.0
